version: '3.1'
services:
  mssql:
    image:  mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Akvelon123"
      ACCEPT_EULA: "Y"
      MSSQL_BACKUP_DIR: "/backups"
    volumes:
      - dbdata:/var/opt/mssql
      - ./backups:/backups
    ports:
      - "1436:1433"
  server:
    build:
      context: ./
      dockerfile: marketplace.dockerfile
    image: marketplace
    ports:
      - 8081:80
    volumes:
      - ./Server/appsettings.json:/app/appsettings.json  
      - ./Server/wwwroot/images:/app/wwwroot/images
    depends_on: 
      - mssql

volumes:
  dbdata:
    driver: local