name: GitHub Actions Demo
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mikhailshaganov
          password: Eyelazorz23

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: marketplace.dockerfile
          push: true
          tags: mikhailshaganov/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


# stages:
#   - build
#   # - test

# .docker:
#   tags:
#     - dind

# before_script:
#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# build-job:
#   extends: .docker
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
#     - docker build -t gitlab.akvelon.net:9444/mikhail.shaganov/marketplace/server -f marketplace.dockerfile .
#     - docker push gitlab.akvelon.net:9444/mikhail.shaganov/marketplace/server