name: GitHub Actions Demo
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: marketplace.dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

